import {
  FORBIDDEN_CODE,
  ERROR_CODE,
  NOT_FOUND_CODE,
  SUCCESS_CODE,
  UNAUTHORIZED_CODE,
} from "./constant";
export const StatusCode = Object.freeze({
  SUCCESS: SUCCESS_CODE,
  ERROR: ERROR_CODE,
  NOT_FOUND: NOT_FOUND_CODE,
  UNAUTHORIZED: UNAUTHORIZED_CODE,
  FORBIDDEN: FORBIDDEN_CODE,
});
